approvedGitRepositories:
  - "**"

enableScripts: true

logFilters:
  - code: YN0060
    level: discard
    text: "@tanstack/eslint-plugin-query"
  - code: YN0002
    level: discard
    text: "@rolldown/plugin-babel"

nodeLinker: node-modules

packageExtensions:
  "@napi-rs/wasm-runtime@*":
    peerDependenciesMeta:
      "@emnapi/core":
        optional: true
      "@emnapi/runtime":
        optional: true
