nodeLinker: node-modules

logFilters:
  - text: "@tanstack/eslint-plugin-query"
    code: YN0060
    level: discard
  - text: "@rolldown/plugin-babel"
    code: YN0002
    level: discard

packageExtensions:
  "@napi-rs/wasm-runtime@*":
    peerDependenciesMeta:
      "@emnapi/core":
        optional: true
      "@emnapi/runtime":
        optional: true
