namespace BudgetBoard.Service.Models;

public static class TransactionCategoriesConstants
{
    public static readonly IEnumerable<ITransactionCategory> DefaultTransactionCategories =
        new List<ITransactionCategory>(
            [
                new TransactionCategoryBase { Value = "Auto & Transport", Parent = "" },
                new TransactionCategoryBase
                {
                    Value = "Auto Insurance",
                    Parent = "Auto & Transport",
                },
                new TransactionCategoryBase { Value = "Auto Payment", Parent = "Auto & Transport" },
                new TransactionCategoryBase { Value = "Gas & Fuel", Parent = "Auto & Transport" },
                new TransactionCategoryBase { Value = "Parking", Parent = "Auto & Transport" },
                new TransactionCategoryBase
                {
                    Value = "Public Transportation",
                    Parent = "Auto & Transport",
                },
                new TransactionCategoryBase { Value = "Ride Share", Parent = "Auto & Transport" },
                new TransactionCategoryBase
                {
                    Value = "Service & Parts",
                    Parent = "Auto & Transport",
                },
                new TransactionCategoryBase { Value = "Bills & Utilities", Parent = "" },
                new TransactionCategoryBase { Value = "Internet", Parent = "Bills & Utilities" },
                new TransactionCategoryBase
                {
                    Value = "Mobile Phone",
                    Parent = "Bills & Utilities",
                },
                new TransactionCategoryBase { Value = "Television", Parent = "Bills & Utilities" },
                new TransactionCategoryBase { Value = "Utilities", Parent = "Bills & Utilities" },
                new TransactionCategoryBase { Value = "Education", Parent = "" },
                new TransactionCategoryBase { Value = "Books & Supplies", Parent = "Education" },
                new TransactionCategoryBase { Value = "Student Loan", Parent = "Education" },
                new TransactionCategoryBase { Value = "Tuition", Parent = "Education" },
                new TransactionCategoryBase { Value = "Entertainment", Parent = "" },
                new TransactionCategoryBase { Value = "Activities", Parent = "Entertainment" },
                new TransactionCategoryBase { Value = "Arts", Parent = "Entertainment" },
                new TransactionCategoryBase { Value = "Movies", Parent = "Entertainment" },
                new TransactionCategoryBase { Value = "Music", Parent = "Entertainment" },
                new TransactionCategoryBase { Value = "Books", Parent = "Entertainment" },
                new TransactionCategoryBase { Value = "Games", Parent = "Entertainment" },
                new TransactionCategoryBase { Value = "Fees & Charges", Parent = "" },
                new TransactionCategoryBase { Value = "ATM Fee", Parent = "Fees & Charges" },
                new TransactionCategoryBase { Value = "Bank Fee", Parent = "Fees & Charges" },
                new TransactionCategoryBase { Value = "Finance Charge", Parent = "Fees & Charges" },
                new TransactionCategoryBase { Value = "Late Fee", Parent = "Fees & Charges" },
                new TransactionCategoryBase { Value = "Service Fee", Parent = "Fees & Charges" },
                new TransactionCategoryBase
                {
                    Value = "Trade Commissions",
                    Parent = "Fees & Charges",
                },
                new TransactionCategoryBase { Value = "Financial", Parent = "" },
                new TransactionCategoryBase { Value = "Roth IRA", Parent = "Financial" },
                new TransactionCategoryBase { Value = "Investment", Parent = "Financial" },
                new TransactionCategoryBase { Value = "Food & Dining", Parent = "" },
                new TransactionCategoryBase { Value = "Alcohol & Bars", Parent = "Food & Dining" },
                new TransactionCategoryBase { Value = "Coffee Shops", Parent = "Food & Dining" },
                new TransactionCategoryBase { Value = "Food Delivery", Parent = "Food & Dining" },
                new TransactionCategoryBase { Value = "Groceries", Parent = "Food & Dining" },
                new TransactionCategoryBase { Value = "Restaurants", Parent = "Food & Dining" },
                new TransactionCategoryBase { Value = "Gifts & Donations", Parent = "" },
                new TransactionCategoryBase { Value = "Charity", Parent = "Gifts & Donations" },
                new TransactionCategoryBase { Value = "Gift", Parent = "Gifts & Donations" },
                new TransactionCategoryBase { Value = "Goals", Parent = "" },
                new TransactionCategoryBase { Value = "Health & Fitness", Parent = "" },
                new TransactionCategoryBase { Value = "Dentist", Parent = "Health & Fitness" },
                new TransactionCategoryBase { Value = "Doctor", Parent = "Health & Fitness" },
                new TransactionCategoryBase { Value = "Eyecare", Parent = "Health & Fitness" },
                new TransactionCategoryBase { Value = "Gym", Parent = "Health & Fitness" },
                new TransactionCategoryBase
                {
                    Value = "Health Insurance",
                    Parent = "Health & Fitness",
                },
                new TransactionCategoryBase { Value = "Pharmacy", Parent = "Health & Fitness" },
                new TransactionCategoryBase { Value = "Sports", Parent = "Health & Fitness" },
                new TransactionCategoryBase { Value = "Hide from Budgets", Parent = "" },
                new TransactionCategoryBase { Value = "Home", Parent = "" },
                new TransactionCategoryBase { Value = "Furnishings", Parent = "Home" },
                new TransactionCategoryBase { Value = "Home Improvement", Parent = "Home" },
                new TransactionCategoryBase { Value = "Home Insurance", Parent = "Home" },
                new TransactionCategoryBase { Value = "Home Services", Parent = "Home" },
                new TransactionCategoryBase { Value = "Home Supplies", Parent = "Home" },
                new TransactionCategoryBase { Value = "Lawn & Garden", Parent = "Home" },
                new TransactionCategoryBase { Value = "Mortgage & Rent", Parent = "Home" },
                new TransactionCategoryBase { Value = "Income", Parent = "" },
                new TransactionCategoryBase { Value = "Bonus", Parent = "Income" },
                new TransactionCategoryBase { Value = "Interest Income", Parent = "Income" },
                new TransactionCategoryBase { Value = "Paycheck", Parent = "Income" },
                new TransactionCategoryBase { Value = "Reimbursements", Parent = "Income" },
                new TransactionCategoryBase { Value = "Tax Return", Parent = "Income" },
                new TransactionCategoryBase { Value = "Investments", Parent = "" },
                new TransactionCategoryBase { Value = "Buy", Parent = "Investments" },
                new TransactionCategoryBase { Value = "Deposit", Parent = "Investments" },
                new TransactionCategoryBase
                {
                    Value = "Dividend & Cap Gains",
                    Parent = "Investments",
                },
                new TransactionCategoryBase { Value = "Sell", Parent = "Investments" },
                new TransactionCategoryBase { Value = "Withdrawl", Parent = "Investments" },
                new TransactionCategoryBase { Value = "Loans", Parent = "" },
                new TransactionCategoryBase { Value = "Loan Fees & Charges", Parent = "Loans" },
                new TransactionCategoryBase { Value = "Loan Insurance", Parent = "Loans" },
                new TransactionCategoryBase { Value = "Loan Interest", Parent = "Loans" },
                new TransactionCategoryBase { Value = "Loan Payments", Parent = "Loans" },
                new TransactionCategoryBase { Value = "Loan Principal", Parent = "Loans" },
                new TransactionCategoryBase { Value = "Misc", Parent = "" },
                new TransactionCategoryBase { Value = "Personal Care", Parent = "" },
                new TransactionCategoryBase { Value = "Hair", Parent = "Personal Care" },
                new TransactionCategoryBase { Value = "Laundry", Parent = "Personal Care" },
                new TransactionCategoryBase { Value = "Spa & Massage", Parent = "Personal Care" },
                new TransactionCategoryBase { Value = "Pets", Parent = "" },
                new TransactionCategoryBase { Value = "Pet Food & Supplies", Parent = "Pets" },
                new TransactionCategoryBase { Value = "Pet Grooming", Parent = "Pets" },
                new TransactionCategoryBase { Value = "Veterinary", Parent = "Pets" },
                new TransactionCategoryBase { Value = "Shopping", Parent = "" },
                new TransactionCategoryBase { Value = "Clothing", Parent = "Shopping" },
                new TransactionCategoryBase
                {
                    Value = "Electronics & Software",
                    Parent = "Shopping",
                },
                new TransactionCategoryBase { Value = "Hobbies", Parent = "Shopping" },
                new TransactionCategoryBase { Value = "Household", Parent = "Shopping" },
                new TransactionCategoryBase { Value = "Taxes", Parent = "" },
                new TransactionCategoryBase { Value = "Federal Tax", Parent = "Taxes" },
                new TransactionCategoryBase { Value = "Local Tax", Parent = "Taxes" },
                new TransactionCategoryBase { Value = "Property Tax", Parent = "Taxes" },
                new TransactionCategoryBase { Value = "Sales Tax", Parent = "Taxes" },
                new TransactionCategoryBase { Value = "State Tax", Parent = "Taxes" },
                new TransactionCategoryBase { Value = "Transfer", Parent = "" },
                new TransactionCategoryBase { Value = "Credit Card Payment", Parent = "Transfer" },
                new TransactionCategoryBase { Value = "Travel", Parent = "" },
                new TransactionCategoryBase { Value = "Air Travel", Parent = "Travel" },
                new TransactionCategoryBase { Value = "Hotel", Parent = "Travel" },
                new TransactionCategoryBase { Value = "Rental Car & Taxi", Parent = "Travel" },
                new TransactionCategoryBase { Value = "Vacation", Parent = "Travel" },
                new TransactionCategoryBase { Value = "Other", Parent = "" },
            ]
        );
}
