# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  backend:
    image: money-minder-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - Logging__LogLevel__Default=Information
  client:
    image: money-minder-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
