# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  backend:
    image: moneyminder-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - Logging__LogLevel__Default=Information
    ports:
      - 8080:80
  client:
    image: moneyminder-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        VITE_API_URL: http://0.0.0.0:8080
    ports:
      - 80:80
    depends_on:
      - backend
