# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  backend:
    image: budget-board-server
    container_name: backend
    hostname: backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - Logging__LogLevel__Default=Information
  client:
    image: budget-board-client
    container_name: client
    hostname: client
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client/certs/budgetboard.net.crt:/etc/ssl/certs/budgetboard.net.crt:ro
      - ./client/certs/budgetboard.net.key:/etc/ssl/private/budgetboard.net.key:ro
    depends_on:
      - backend
