services:
  server:
    container_name: budget-board-server
    restart: unless-stopped
    build: ./server
    environment:
      - Logging__LogLevel__Default=Information
  client:
    container_name: client
    restart: unless-stopped
    build: ./client
    depends_on:
      - server
  db:
    container_name: postgres-db
    image: postgres:16
    restart: unlesss-stopped
    ports:
      - "5432:5432"
    profiles:
      - "include-db"
    depends_on:
      - server
