export interface ICategoryIconOption {
  icon: string;
  keywords: string[];
}

export interface ICategoryIconGroup {
  labelKey: string;
  icons: ICategoryIconOption[];
}

/**
 * The icons offered by the category icon picker, grouped for browsing.
 *
 * Keywords are written in English and are matched by prefix by
 * filterCategoryIconGroups, so "pet" finds the animals without also
 * turning up "trumpet". They are intentionally not translated: a
 * per-icon keyword list would multiply the translation burden many times
 * over. Searching by the translated group name is handled instead.
 */
export const CATEGORY_ICON_GROUPS: ICategoryIconGroup[] = [
  {
    labelKey: "icon_group_money",
    icons: [
      { icon: "💰", keywords: ["money", "savings", "bag"] },
      { icon: "💵", keywords: ["cash", "dollar", "bill"] },
      { icon: "💴", keywords: ["yen", "money"] },
      { icon: "💶", keywords: ["euro", "money"] },
      { icon: "💷", keywords: ["pound", "money"] },
      { icon: "🪙", keywords: ["coin", "change"] },
      { icon: "💳", keywords: ["card", "credit", "debit", "payment"] },
      { icon: "🏦", keywords: ["bank"] },
      { icon: "🏧", keywords: ["atm", "cash", "machine"] },
      { icon: "💸", keywords: ["spending", "expense"] },
      { icon: "🧾", keywords: ["receipt", "invoice", "bill"] },
      { icon: "📈", keywords: ["chart", "growth", "investment", "increase"] },
      { icon: "📉", keywords: ["chart", "loss", "decrease"] },
      { icon: "📊", keywords: ["chart", "stats", "report"] },
      { icon: "💹", keywords: ["market", "stocks"] },
      { icon: "🧮", keywords: ["abacus", "accounting", "budget"] },
      { icon: "🤑", keywords: ["rich", "wealthy"] },
      { icon: "💎", keywords: ["gem", "diamond", "valuable"] },
      { icon: "🔐", keywords: ["vault", "secure"] },
      { icon: "📑", keywords: ["statement", "documents"] },
    ],
  },
  {
    labelKey: "icon_group_home",
    icons: [
      { icon: "🏠", keywords: ["house", "home"] },
      { icon: "🏡", keywords: ["house", "garden"] },
      { icon: "🏘️", keywords: ["houses", "neighborhood"] },
      { icon: "🏚️", keywords: ["derelict", "repair"] },
      { icon: "🛋️", keywords: ["couch", "sofa", "furniture"] },
      { icon: "🛏️", keywords: ["bed", "bedroom", "furniture"] },
      { icon: "🚪", keywords: ["door"] },
      { icon: "🪟", keywords: ["window"] },
      { icon: "🚿", keywords: ["shower", "bathroom"] },
      { icon: "🛁", keywords: ["bath", "bathroom"] },
      { icon: "🚽", keywords: ["toilet", "plumbing"] },
      { icon: "🧹", keywords: ["broom", "cleaning"] },
      { icon: "🧺", keywords: ["laundry", "basket"] },
      { icon: "🧽", keywords: ["sponge", "cleaning"] },
      { icon: "🪣", keywords: ["bucket", "cleaning"] },
      { icon: "🧼", keywords: ["soap", "cleaning"] },
      { icon: "🔧", keywords: ["wrench", "repair", "maintenance"] },
      { icon: "🔨", keywords: ["hammer", "repair"] },
      { icon: "🪛", keywords: ["screwdriver", "repair"] },
      { icon: "🧰", keywords: ["toolbox", "repair"] },
      { icon: "🪜", keywords: ["ladder", "repair"] },
      { icon: "🔑", keywords: ["key", "keys", "rent"] },
      { icon: "🗝️", keywords: ["key", "old"] },
      { icon: "💡", keywords: ["lightbulb", "electricity"] },
      { icon: "🕯️", keywords: ["candle"] },
      { icon: "🧯", keywords: ["extinguisher", "safety"] },
      { icon: "🪴", keywords: ["plant", "house", "indoor"] },
      { icon: "🌳", keywords: ["tree", "yard"] },
      { icon: "🌱", keywords: ["seedling", "garden", "lawn"] },
      { icon: "📦", keywords: ["box", "moving", "package"] },
    ],
  },
  {
    labelKey: "icon_group_food",
    icons: [
      { icon: "🍎", keywords: ["apple", "fruit"] },
      { icon: "🍌", keywords: ["banana", "fruit"] },
      { icon: "🍇", keywords: ["grapes", "fruit"] },
      { icon: "🍓", keywords: ["strawberry", "fruit"] },
      { icon: "🍉", keywords: ["watermelon", "fruit"] },
      { icon: "🍊", keywords: ["orange", "fruit"] },
      { icon: "🥑", keywords: ["avocado"] },
      { icon: "🥕", keywords: ["carrot", "vegetable"] },
      { icon: "🍅", keywords: ["tomato", "vegetable"] },
      { icon: "🥦", keywords: ["broccoli", "vegetable"] },
      { icon: "🥔", keywords: ["potato", "vegetable"] },
      { icon: "🌽", keywords: ["corn", "vegetable"] },
      { icon: "🍞", keywords: ["bread", "bakery"] },
      { icon: "🥐", keywords: ["croissant", "bakery"] },
      { icon: "🥖", keywords: ["baguette", "bakery"] },
      { icon: "🧀", keywords: ["cheese", "dairy"] },
      { icon: "🥚", keywords: ["egg"] },
      { icon: "🥛", keywords: ["milk", "dairy"] },
      { icon: "🥩", keywords: ["meat", "steak"] },
      { icon: "🍗", keywords: ["chicken", "poultry"] },
      { icon: "🥓", keywords: ["bacon"] },
      { icon: "🍔", keywords: ["burger", "fast", "food"] },
      { icon: "🍟", keywords: ["fries", "fast", "food"] },
      { icon: "🍕", keywords: ["pizza"] },
      { icon: "🌭", keywords: ["hotdog", "fast", "food"] },
      { icon: "🌮", keywords: ["taco"] },
      { icon: "🌯", keywords: ["burrito"] },
      { icon: "🥪", keywords: ["sandwich"] },
      { icon: "🥗", keywords: ["salad"] },
      { icon: "🍜", keywords: ["noodles", "ramen"] },
      { icon: "🍝", keywords: ["pasta", "spaghetti"] },
      { icon: "🍲", keywords: ["stew", "soup"] },
      { icon: "🍛", keywords: ["curry", "rice"] },
      { icon: "🍣", keywords: ["sushi"] },
      { icon: "🍤", keywords: ["shrimp", "seafood"] },
      { icon: "🍚", keywords: ["rice"] },
      { icon: "🥟", keywords: ["dumpling"] },
      { icon: "🍿", keywords: ["popcorn", "snack"] },
      { icon: "🥨", keywords: ["pretzel", "snack"] },
      { icon: "🍩", keywords: ["donut", "dessert"] },
      { icon: "🍪", keywords: ["cookie", "dessert"] },
      { icon: "🍰", keywords: ["cake", "dessert"] },
      { icon: "🎂", keywords: ["birthday", "cake"] },
      { icon: "🍫", keywords: ["chocolate", "candy"] },
      { icon: "🍬", keywords: ["candy", "sweets"] },
      { icon: "🍦", keywords: ["ice", "cream", "dessert"] },
      { icon: "☕", keywords: ["coffee", "cafe"] },
      { icon: "🍵", keywords: ["tea"] },
      { icon: "🧃", keywords: ["juice", "drink"] },
      { icon: "🥤", keywords: ["soda", "drink"] },
      { icon: "🍺", keywords: ["beer", "bar"] },
      { icon: "🍻", keywords: ["beers", "drinks"] },
      { icon: "🍷", keywords: ["wine"] },
      { icon: "🍸", keywords: ["cocktail", "bar"] },
      { icon: "🥂", keywords: ["champagne", "toast"] },
      { icon: "🍾", keywords: ["bottle", "champagne"] },
      { icon: "🥃", keywords: ["whiskey", "liquor"] },
      { icon: "🛒", keywords: ["groceries", "cart", "shopping"] },
      { icon: "🧂", keywords: ["salt", "seasoning"] },
      { icon: "🍽️", keywords: ["restaurant", "dining"] },
      { icon: "🥡", keywords: ["takeout", "delivery"] },
    ],
  },
  {
    labelKey: "icon_group_transport",
    icons: [
      { icon: "🚗", keywords: ["car", "auto"] },
      { icon: "🚙", keywords: ["suv", "car"] },
      { icon: "🚐", keywords: ["van"] },
      { icon: "🛻", keywords: ["truck", "pickup"] },
      { icon: "🚚", keywords: ["truck", "delivery"] },
      { icon: "🚛", keywords: ["truck", "freight"] },
      { icon: "🚕", keywords: ["taxi", "cab"] },
      { icon: "🚌", keywords: ["bus"] },
      { icon: "🚎", keywords: ["trolley"] },
      { icon: "🚓", keywords: ["police", "car"] },
      { icon: "🚑", keywords: ["ambulance"] },
      { icon: "🚒", keywords: ["fire", "truck"] },
      { icon: "🏍️", keywords: ["motorcycle"] },
      { icon: "🛵", keywords: ["scooter", "moped"] },
      { icon: "🚲", keywords: ["bicycle", "bike"] },
      { icon: "🛴", keywords: ["scooter", "kick"] },
      { icon: "🛹", keywords: ["skateboard"] },
      { icon: "✈️", keywords: ["plane", "flight", "airline"] },
      { icon: "🛫", keywords: ["departure", "flight"] },
      { icon: "🛬", keywords: ["arrival", "flight"] },
      { icon: "🚁", keywords: ["helicopter"] },
      { icon: "🚀", keywords: ["rocket"] },
      { icon: "⛵", keywords: ["sailboat"] },
      { icon: "🛥️", keywords: ["boat", "motorboat"] },
      { icon: "🚢", keywords: ["ship", "cruise"] },
      { icon: "⛴️", keywords: ["ferry"] },
      { icon: "🚂", keywords: ["train", "locomotive"] },
      { icon: "🚆", keywords: ["train", "rail"] },
      { icon: "🚊", keywords: ["tram"] },
      { icon: "🚇", keywords: ["metro", "subway"] },
      { icon: "🚏", keywords: ["bus", "stop"] },
      { icon: "⛽", keywords: ["gas", "fuel", "petrol"] },
      { icon: "🔌", keywords: ["charging", "electric", "ev", "plug"] },
      { icon: "🅿️", keywords: ["parking"] },
      { icon: "🛞", keywords: ["tire", "wheel"] },
      { icon: "🛠️", keywords: ["service", "repair"] },
      { icon: "🚦", keywords: ["traffic", "light"] },
      { icon: "🛣️", keywords: ["highway", "road", "toll"] },
      { icon: "🚧", keywords: ["construction", "road", "work"] },
    ],
  },
  {
    labelKey: "icon_group_health",
    icons: [
      { icon: "💊", keywords: ["pills", "medication", "pharmacy"] },
      { icon: "💉", keywords: ["injection", "vaccine"] },
      { icon: "🩺", keywords: ["stethoscope", "doctor"] },
      { icon: "🏥", keywords: ["hospital"] },
      { icon: "🩹", keywords: ["bandage", "first", "aid"] },
      { icon: "🩼", keywords: ["crutch", "injury"] },
      { icon: "🦷", keywords: ["tooth", "dentist"] },
      { icon: "👓", keywords: ["glasses", "eye", "care"] },
      { icon: "🕶️", keywords: ["sunglasses"] },
      { icon: "🧑‍⚕️", keywords: ["doctor", "nurse"] },
      { icon: "🫀", keywords: ["heart", "cardiology"] },
      { icon: "🧬", keywords: ["dna", "genetics"] },
      { icon: "🩸", keywords: ["blood", "donation"] },
      { icon: "🧪", keywords: ["lab", "test"] },
      { icon: "🌡️", keywords: ["thermometer", "fever"] },
      { icon: "🧴", keywords: ["lotion", "skin", "care"] },
      { icon: "🪥", keywords: ["toothbrush", "hygiene"] },
      { icon: "🏋️", keywords: ["gym", "weights", "fitness"] },
      { icon: "🤸", keywords: ["gymnastics", "fitness"] },
      { icon: "🧘", keywords: ["yoga", "meditation"] },
      { icon: "🏃", keywords: ["running", "jogging"] },
      { icon: "🚴", keywords: ["cycling"] },
      { icon: "🏊", keywords: ["swimming"] },
      { icon: "⚽", keywords: ["soccer", "football"] },
      { icon: "🏀", keywords: ["basketball"] },
      { icon: "🏈", keywords: ["football"] },
      { icon: "⚾", keywords: ["baseball"] },
      { icon: "🎾", keywords: ["tennis"] },
      { icon: "🏐", keywords: ["volleyball"] },
      { icon: "🏓", keywords: ["ping", "pong", "table", "tennis"] },
      { icon: "🥊", keywords: ["boxing"] },
      { icon: "⛳", keywords: ["golf"] },
      { icon: "🥋", keywords: ["martial", "arts"] },
    ],
  },
  {
    labelKey: "icon_group_entertainment",
    icons: [
      { icon: "🎬", keywords: ["movies", "film", "cinema"] },
      { icon: "📺", keywords: ["tv", "television", "streaming"] },
      { icon: "📻", keywords: ["radio"] },
      { icon: "🎵", keywords: ["music", "note"] },
      { icon: "🎶", keywords: ["music", "notes"] },
      { icon: "🎧", keywords: ["headphones", "music"] },
      { icon: "🎤", keywords: ["microphone", "karaoke"] },
      { icon: "🎸", keywords: ["guitar"] },
      { icon: "🥁", keywords: ["drums"] },
      { icon: "🎹", keywords: ["piano", "keyboard"] },
      { icon: "🎺", keywords: ["trumpet"] },
      { icon: "🎻", keywords: ["violin"] },
      { icon: "🎮", keywords: ["gaming", "video", "game"] },
      { icon: "🕹️", keywords: ["arcade", "joystick"] },
      { icon: "🎲", keywords: ["dice", "board", "game"] },
      { icon: "♟️", keywords: ["chess"] },
      { icon: "🎱", keywords: ["billiards", "pool"] },
      { icon: "🎳", keywords: ["bowling"] },
      { icon: "🃏", keywords: ["cards", "poker"] },
      { icon: "🧩", keywords: ["puzzle"] },
      { icon: "🎨", keywords: ["art", "painting"] },
      { icon: "🖌️", keywords: ["paintbrush", "art"] },
      { icon: "📚", keywords: ["books", "reading"] },
      { icon: "📖", keywords: ["book", "reading"] },
      { icon: "📰", keywords: ["news", "newspaper"] },
      { icon: "🎟️", keywords: ["ticket", "event"] },
      { icon: "🎪", keywords: ["circus"] },
      { icon: "🎭", keywords: ["theater"] },
      { icon: "🎡", keywords: ["ferris", "wheel", "amusement"] },
      { icon: "🎢", keywords: ["roller", "coaster", "amusement"] },
      { icon: "🎠", keywords: ["carousel"] },
    ],
  },
  {
    labelKey: "icon_group_shopping",
    icons: [
      { icon: "🛍️", keywords: ["shopping", "bags", "retail"] },
      { icon: "👕", keywords: ["shirt", "clothes"] },
      { icon: "👖", keywords: ["jeans", "pants"] },
      { icon: "👗", keywords: ["dress", "clothes"] },
      { icon: "👔", keywords: ["tie", "formal"] },
      { icon: "🧥", keywords: ["coat", "jacket"] },
      { icon: "🩳", keywords: ["shorts"] },
      { icon: "🧦", keywords: ["socks"] },
      { icon: "🧤", keywords: ["gloves"] },
      { icon: "🧣", keywords: ["scarf"] },
      { icon: "👞", keywords: ["shoes", "formal"] },
      { icon: "👟", keywords: ["sneakers", "shoes"] },
      { icon: "👠", keywords: ["heels", "shoes"] },
      { icon: "🥾", keywords: ["boots"] },
      { icon: "🧢", keywords: ["cap", "hat"] },
      { icon: "👑", keywords: ["crown"] },
      { icon: "🎒", keywords: ["backpack"] },
      { icon: "👜", keywords: ["handbag", "purse"] },
      { icon: "👛", keywords: ["coin", "purse"] },
      { icon: "💄", keywords: ["makeup", "cosmetics"] },
      { icon: "💍", keywords: ["ring", "jewelry"] },
      { icon: "📿", keywords: ["necklace", "jewelry"] },
      { icon: "⌚", keywords: ["watch"] },
      { icon: "🕰️", keywords: ["clock"] },
      { icon: "🧵", keywords: ["thread", "sewing"] },
      { icon: "🧶", keywords: ["yarn", "knitting"] },
      { icon: "🪡", keywords: ["needle", "sewing"] },
    ],
  },
  {
    labelKey: "icon_group_technology",
    icons: [
      { icon: "📱", keywords: ["phone", "mobile"] },
      { icon: "💻", keywords: ["laptop", "computer"] },
      { icon: "🖥️", keywords: ["desktop", "monitor"] },
      { icon: "⌨️", keywords: ["keyboard"] },
      { icon: "🖱️", keywords: ["mouse"] },
      { icon: "🖨️", keywords: ["printer"] },
      { icon: "💾", keywords: ["disk", "storage"] },
      { icon: "💿", keywords: ["disc", "cd"] },
      { icon: "📀", keywords: ["dvd"] },
      { icon: "🔋", keywords: ["battery"] },
      { icon: "📷", keywords: ["camera", "photo"] },
      { icon: "📸", keywords: ["camera", "flash"] },
      { icon: "🎥", keywords: ["camcorder", "video"] },
      { icon: "📹", keywords: ["video", "camera"] },
      { icon: "📡", keywords: ["satellite", "dish", "internet"] },
      { icon: "🛰️", keywords: ["satellite"] },
      { icon: "🌐", keywords: ["internet", "web", "domain"] },
      { icon: "📶", keywords: ["signal", "data"] },
      { icon: "☎️", keywords: ["telephone", "landline"] },
      { icon: "📞", keywords: ["phone", "call"] },
      { icon: "📠", keywords: ["fax"] },
      { icon: "🔦", keywords: ["flashlight"] },
      { icon: "🔒", keywords: ["lock", "security"] },
      { icon: "🔓", keywords: ["unlock"] },
      { icon: "🖲️", keywords: ["trackball"] },
      { icon: "🧑‍💻", keywords: ["developer", "programming"] },
      { icon: "⚙️", keywords: ["settings", "gear"] },
    ],
  },
  {
    labelKey: "icon_group_work",
    icons: [
      { icon: "💼", keywords: ["work", "business", "job"] },
      { icon: "🏢", keywords: ["office", "building"] },
      { icon: "🏭", keywords: ["factory", "industry"] },
      { icon: "📁", keywords: ["folder", "files"] },
      { icon: "📂", keywords: ["open", "folder"] },
      { icon: "🗂️", keywords: ["dividers", "organize"] },
      { icon: "📋", keywords: ["clipboard", "list"] },
      { icon: "📝", keywords: ["memo", "notes"] },
      { icon: "✏️", keywords: ["pencil"] },
      { icon: "🖊️", keywords: ["pen"] },
      { icon: "🖍️", keywords: ["crayon"] },
      { icon: "📐", keywords: ["ruler", "triangle"] },
      { icon: "📏", keywords: ["ruler"] },
      { icon: "✂️", keywords: ["scissors"] },
      { icon: "📎", keywords: ["paperclip"] },
      { icon: "📌", keywords: ["pin"] },
      { icon: "📅", keywords: ["calendar", "date"] },
      { icon: "🗓️", keywords: ["calendar", "spiral"] },
      { icon: "⏰", keywords: ["alarm", "time"] },
      { icon: "⏳", keywords: ["hourglass", "time"] },
      { icon: "🎓", keywords: ["graduation", "education", "tuition"] },
      { icon: "🏫", keywords: ["school"] },
      { icon: "🔬", keywords: ["microscope", "science"] },
      { icon: "🔭", keywords: ["telescope"] },
      { icon: "⚖️", keywords: ["scales", "legal", "law"] },
      { icon: "🏛️", keywords: ["government", "institution"] },
      { icon: "📮", keywords: ["mailbox", "post"] },
      { icon: "✉️", keywords: ["envelope", "mail"] },
      { icon: "📧", keywords: ["email"] },
      { icon: "🖇️", keywords: ["paperclips"] },
      { icon: "🗄️", keywords: ["cabinet", "filing"] },
    ],
  },
  {
    labelKey: "icon_group_travel",
    icons: [
      { icon: "🧳", keywords: ["luggage", "suitcase"] },
      { icon: "🏖️", keywords: ["beach", "vacation"] },
      { icon: "⛱️", keywords: ["umbrella", "beach"] },
      { icon: "🏝️", keywords: ["island", "tropical"] },
      { icon: "🗺️", keywords: ["map", "travel"] },
      { icon: "🧭", keywords: ["compass", "navigation"] },
      { icon: "🏕️", keywords: ["camping"] },
      { icon: "⛺", keywords: ["tent", "camping"] },
      { icon: "🛎️", keywords: ["hotel", "bell", "service"] },
      { icon: "🏨", keywords: ["hotel"] },
      { icon: "🗽", keywords: ["statue", "landmark"] },
      { icon: "🗼", keywords: ["tower", "landmark"] },
      { icon: "🏰", keywords: ["castle"] },
      { icon: "⛩️", keywords: ["shrine"] },
      { icon: "🕌", keywords: ["mosque"] },
      { icon: "⛪", keywords: ["church"] },
      { icon: "🕍", keywords: ["synagogue"] },
      { icon: "🌋", keywords: ["volcano"] },
      { icon: "🏔️", keywords: ["mountain", "snow"] },
      { icon: "⛰️", keywords: ["mountain"] },
      { icon: "🌅", keywords: ["sunrise"] },
      { icon: "🌄", keywords: ["sunrise", "mountains"] },
      { icon: "🚞", keywords: ["mountain", "railway"] },
      { icon: "🛶", keywords: ["canoe", "kayak"] },
      { icon: "🪂", keywords: ["paragliding"] },
      { icon: "🏂", keywords: ["snowboarding"] },
      { icon: "⛷️", keywords: ["skiing"] },
      { icon: "🎿", keywords: ["skis"] },
      { icon: "🧗", keywords: ["climbing"] },
    ],
  },
  {
    labelKey: "icon_group_family",
    icons: [
      { icon: "👶", keywords: ["baby", "infant"] },
      { icon: "🧒", keywords: ["child", "kid"] },
      { icon: "👦", keywords: ["boy"] },
      { icon: "👧", keywords: ["girl"] },
      { icon: "🧑", keywords: ["person", "adult"] },
      { icon: "👨", keywords: ["man"] },
      { icon: "👩", keywords: ["woman"] },
      { icon: "👴", keywords: ["grandfather", "elderly"] },
      { icon: "👵", keywords: ["grandmother", "elderly"] },
      { icon: "👨‍👩‍👧‍👦", keywords: ["family"] },
      { icon: "🤝", keywords: ["partnership", "handshake"] },
      { icon: "🐶", keywords: ["dog", "puppy", "pet"] },
      { icon: "🐱", keywords: ["cat", "kitten", "pet"] },
      { icon: "🐭", keywords: ["mouse", "pet"] },
      { icon: "🐹", keywords: ["hamster", "pet"] },
      { icon: "🐰", keywords: ["rabbit", "bunny", "pet"] },
      { icon: "🦊", keywords: ["fox"] },
      { icon: "🐻", keywords: ["bear"] },
      { icon: "🐼", keywords: ["panda"] },
      { icon: "🐨", keywords: ["koala"] },
      { icon: "🐯", keywords: ["tiger"] },
      { icon: "🦁", keywords: ["lion"] },
      { icon: "🐮", keywords: ["cow"] },
      { icon: "🐷", keywords: ["pig"] },
      { icon: "🐸", keywords: ["frog"] },
      { icon: "🐔", keywords: ["chicken"] },
      { icon: "🐧", keywords: ["penguin"] },
      { icon: "🐦", keywords: ["bird"] },
      { icon: "🦆", keywords: ["duck"] },
      { icon: "🦉", keywords: ["owl"] },
      { icon: "🐺", keywords: ["wolf"] },
      { icon: "🐴", keywords: ["horse"] },
      { icon: "🦄", keywords: ["unicorn"] },
      { icon: "🐝", keywords: ["bee"] },
      { icon: "🦋", keywords: ["butterfly"] },
      { icon: "🐢", keywords: ["turtle"] },
      { icon: "🐍", keywords: ["snake"] },
      { icon: "🐙", keywords: ["octopus"] },
      { icon: "🐠", keywords: ["fish", "tropical"] },
      { icon: "🐟", keywords: ["fish"] },
      { icon: "🐬", keywords: ["dolphin"] },
      { icon: "🐳", keywords: ["whale"] },
      { icon: "🦈", keywords: ["shark"] },
      { icon: "🐾", keywords: ["paw", "pet", "vet"] },
    ],
  },
  {
    labelKey: "icon_group_celebrations",
    icons: [
      { icon: "🎁", keywords: ["gift", "present"] },
      { icon: "🎀", keywords: ["ribbon", "bow"] },
      { icon: "🎉", keywords: ["party", "celebration"] },
      { icon: "🎊", keywords: ["confetti", "celebration"] },
      { icon: "🥳", keywords: ["party", "face"] },
      { icon: "🎈", keywords: ["balloon", "party"] },
      { icon: "🪅", keywords: ["pinata", "party"] },
      { icon: "🧧", keywords: ["envelope", "money", "gift"] },
      { icon: "💐", keywords: ["bouquet", "flowers"] },
      { icon: "🌹", keywords: ["rose", "flower"] },
      { icon: "🌷", keywords: ["tulip", "flower"] },
      { icon: "🌻", keywords: ["sunflower"] },
      { icon: "🌸", keywords: ["blossom", "flower"] },
      { icon: "💒", keywords: ["wedding"] },
      { icon: "💌", keywords: ["love", "letter"] },
      { icon: "❤️", keywords: ["heart", "love"] },
      { icon: "💝", keywords: ["heart", "gift"] },
      { icon: "🎄", keywords: ["christmas", "tree"] },
      { icon: "🎃", keywords: ["halloween", "pumpkin"] },
      { icon: "🦃", keywords: ["thanksgiving", "turkey"] },
      { icon: "🎆", keywords: ["fireworks"] },
      { icon: "🎇", keywords: ["sparkler"] },
      { icon: "🎅", keywords: ["santa", "christmas"] },
      { icon: "🕎", keywords: ["hanukkah", "menorah"] },
      { icon: "🪔", keywords: ["diwali", "lamp"] },
    ],
  },
  {
    labelKey: "icon_group_symbols",
    icons: [
      { icon: "⭐", keywords: ["star", "favorite"] },
      { icon: "🌟", keywords: ["glowing", "star"] },
      { icon: "💫", keywords: ["dizzy", "sparkle"] },
      { icon: "✨", keywords: ["sparkles"] },
      { icon: "🔥", keywords: ["fire", "hot", "streak"] },
      { icon: "💧", keywords: ["water", "drop"] },
      { icon: "☀️", keywords: ["sun", "sunny"] },
      { icon: "🌙", keywords: ["moon", "night"] },
      { icon: "☁️", keywords: ["cloud"] },
      { icon: "⛈️", keywords: ["storm", "weather"] },
      { icon: "❄️", keywords: ["snow", "winter"] },
      { icon: "🌈", keywords: ["rainbow"] },
      { icon: "⚡", keywords: ["lightning", "power"] },
      { icon: "♻️", keywords: ["recycle", "waste"] },
      { icon: "✅", keywords: ["check", "done"] },
      { icon: "❗", keywords: ["important"] },
      { icon: "❓", keywords: ["question"] },
      { icon: "💬", keywords: ["comment", "message"] },
      { icon: "💭", keywords: ["thought"] },
      { icon: "🔔", keywords: ["bell", "notification"] },
      { icon: "🔕", keywords: ["mute"] },
      { icon: "📍", keywords: ["location", "pin"] },
      { icon: "🚩", keywords: ["flag"] },
      { icon: "🎯", keywords: ["goal", "target"] },
      { icon: "🧿", keywords: ["charm"] },
      { icon: "🔮", keywords: ["crystal", "future"] },
      { icon: "🔗", keywords: ["link", "chain"] },
      { icon: "🏷️", keywords: ["tag", "label"] },
      { icon: "🆕", keywords: ["new"] },
    ],
  },
];

/**
 * Filters the icon groups down to the icons matching a search term.
 *
 * A group whose own label matches is kept whole, so that browsing by group
 * name keeps working in languages the English keywords do not cover. Groups
 * left with no icons are dropped.
 *
 * @param {string} search - The search term entered by the user.
 * @param {function} getGroupLabel - Resolves a group's translated label.
 * @returns {ICategoryIconGroup[]} The groups that still have icons to show.
 */
export const filterCategoryIconGroups = (
  search: string,
  getGroupLabel: (group: ICategoryIconGroup) => string,
): ICategoryIconGroup[] => {
  const term = search.trim().toLowerCase();

  if (term.length === 0) {
    return CATEGORY_ICON_GROUPS;
  }

  return CATEGORY_ICON_GROUPS.map((group) => {
    if (getGroupLabel(group).toLowerCase().includes(term)) {
      return group;
    }

    return {
      ...group,
      icons: group.icons.filter((option) =>
        option.keywords.some((keyword) => keyword.startsWith(term)),
      ),
    };
  }).filter((group) => group.icons.length > 0);
};
