name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./client
            image: budget-board-client
          - dockerfile: ./server
            image: budget-board-server

    steps:
      - uses: actions/checkout@v3

      - name: Rename file
        run: mv "client/nginx(http).conf.example" client/nginx.conf

      - name: Delete file
        run: rm -f "client/nginx(http).conf.example"

      - name: Build the Docker image
        run: docker build ${{ matrix.dockerfile }} --tag ${{ matrix.image }}:$(date +%s)
